// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    name, devourer_level, feat_tiers, other_multiplier, group_bonus_count, leftover_shards, legendary_counts, experiment_levels, possessed_runes, possessed_legendaries, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id
`

type CreatePlanParams struct {
	Name                 string                `json:"name"`
	DevourerLevel        sql.NullInt32         `json:"devourer_level"`
	FeatTiers            sql.NullInt32         `json:"feat_tiers"`
	OtherMultiplier      sql.NullFloat64       `json:"other_multiplier"`
	GroupBonusCount      sql.NullInt32         `json:"group_bonus_count"`
	LeftoverShards       sql.NullInt32         `json:"leftover_shards"`
	LegendaryCounts      pqtype.NullRawMessage `json:"legendary_counts"`
	ExperimentLevels     pqtype.NullRawMessage `json:"experiment_levels"`
	PossessedRunes       pqtype.NullRawMessage `json:"possessed_runes"`
	PossessedLegendaries pqtype.NullRawMessage `json:"possessed_legendaries"`
	Notes                sql.NullString        `json:"notes"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createPlan,
		arg.Name,
		arg.DevourerLevel,
		arg.FeatTiers,
		arg.OtherMultiplier,
		arg.GroupBonusCount,
		arg.LeftoverShards,
		arg.LegendaryCounts,
		arg.ExperimentLevels,
		arg.PossessedRunes,
		arg.PossessedLegendaries,
		arg.Notes,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans
WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePlan, id)
	return err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, devourer_level, feat_tiers, other_multiplier, group_bonus_count, leftover_shards, legendary_counts, experiment_levels, possessed_runes, possessed_legendaries, notes, created_at, updated_at FROM plans
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlan(ctx context.Context, id int32) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DevourerLevel,
		&i.FeatTiers,
		&i.OtherMultiplier,
		&i.GroupBonusCount,
		&i.LeftoverShards,
		&i.LegendaryCounts,
		&i.ExperimentLevels,
		&i.PossessedRunes,
		&i.PossessedLegendaries,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name FROM plans
ORDER BY updated_at DESC
`

type ListPlansRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListPlans(ctx context.Context) ([]ListPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansRow
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans
SET 
    name = $2,
    devourer_level = $3,
    feat_tiers = $4,
    other_multiplier = $5,
    group_bonus_count = $6,
    leftover_shards = $7,
    legendary_counts = $8,
    experiment_levels = $9,
    possessed_runes = $10,
    possessed_legendaries = $11,
    notes = $12,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdatePlanParams struct {
	ID                   int32                 `json:"id"`
	Name                 string                `json:"name"`
	DevourerLevel        sql.NullInt32         `json:"devourer_level"`
	FeatTiers            sql.NullInt32         `json:"feat_tiers"`
	OtherMultiplier      sql.NullFloat64       `json:"other_multiplier"`
	GroupBonusCount      sql.NullInt32         `json:"group_bonus_count"`
	LeftoverShards       sql.NullInt32         `json:"leftover_shards"`
	LegendaryCounts      pqtype.NullRawMessage `json:"legendary_counts"`
	ExperimentLevels     pqtype.NullRawMessage `json:"experiment_levels"`
	PossessedRunes       pqtype.NullRawMessage `json:"possessed_runes"`
	PossessedLegendaries pqtype.NullRawMessage `json:"possessed_legendaries"`
	Notes                sql.NullString        `json:"notes"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.DevourerLevel,
		arg.FeatTiers,
		arg.OtherMultiplier,
		arg.GroupBonusCount,
		arg.LeftoverShards,
		arg.LegendaryCounts,
		arg.ExperimentLevels,
		arg.PossessedRunes,
		arg.PossessedLegendaries,
		arg.Notes,
	)
	return err
}
