// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreatePlan(ctx context.Context, arg CreatePlanParams) (int32, error)
	DeletePlan(ctx context.Context, id int32) error
	GetPlan(ctx context.Context, id int32) (Plan, error)
	ListPlans(ctx context.Context) ([]ListPlansRow, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) error
}

var _ Querier = (*Queries)(nil)
