// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/plans": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plans"
                ],
                "summary": "List all saved plans",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.PlanSummary"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new plan when id is 0 or omitted, updates an existing plan when id \u003e 0",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plans"
                ],
                "summary": "Create or update a plan",
                "parameters": [
                    {
                        "description": "Plan data",
                        "name": "plan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Plan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Plan"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/plans/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plans"
                ],
                "summary": "Get a plan by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Plan"
                        }
                    },
                    "400": {
                        "description": "invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "plan not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "plans"
                ],
                "summary": "Delete a plan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/recalculate": {
            "post": {
                "description": "Given a plan, returns total Time Shards earned at prestige, experiment costs, rune requirements for planned legendaries, and per-experiment summaries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculator"
                ],
                "summary": "Calculate Time Shards and resource costs for a plan",
                "parameters": [
                    {
                        "description": "Plan to calculate",
                        "name": "plan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Plan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RecalculateResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ExperimentSummary": {
            "type": "object",
            "properties": {
                "currentLevel": {
                    "type": "integer"
                },
                "currentLevelCost": {
                    "type": "string"
                },
                "currentLevelValue": {
                    "type": "string"
                },
                "id": {
                    "$ref": "#/definitions/models.ExperimentID"
                },
                "maxLevel": {
                    "type": "boolean"
                },
                "nextLevelCost": {
                    "type": "string"
                },
                "nextLevelValue": {
                    "type": "string"
                }
            }
        },
        "api.PlanSummary": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.RecalculateResponse": {
            "type": "object",
            "properties": {
                "baseShards": {
                    "type": "integer"
                },
                "experimentCost": {
                    "type": "integer"
                },
                "experiments": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/api.ExperimentSummary"
                    }
                },
                "featMultiplier": {
                    "type": "number"
                },
                "legendMultiplier": {
                    "type": "number"
                },
                "legendaryRunes": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/calculator.RuneCosts"
                    }
                },
                "otherMultiplier": {
                    "type": "number"
                },
                "remaining": {
                    "type": "integer"
                },
                "runeNeeded": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "runeTotal": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "totalShards": {
                    "type": "integer"
                }
            }
        },
        "calculator.RuneCosts": {
            "type": "object",
            "additionalProperties": {
                "type": "integer"
            }
        },
        "models.ExperimentID": {
            "type": "string",
            "enum": [
                "seasoning",
                "strength",
                "taste",
                "capacity",
                "body_snatcher",
                "weakening",
                "damage_cap",
                "ice_chest",
                "poison_chest",
                "blood_chest",
                "moon_chest",
                "death_chest",
                "cosmic_chest",
                "seasoning_2",
                "strength_2",
                "taste_2",
                "capacity_2"
            ],
            "x-enum-varnames": [
                "ExpSeasoning",
                "ExpStrength",
                "ExpTaste",
                "ExpCapacity",
                "ExpBodySnatcher",
                "ExpWeakening",
                "ExpDamageCap",
                "ExpIceChest",
                "ExpPoisonChest",
                "ExpBloodChest",
                "ExpMoonChest",
                "ExpDeathChest",
                "ExpCosmicChest",
                "ExpSeasoning2",
                "ExpStrength2",
                "ExpTaste2",
                "ExpCapacity2"
            ]
        },
        "models.Plan": {
            "type": "object",
            "properties": {
                "devourerLevel": {
                    "type": "integer"
                },
                "experimentLevels": {
                    "description": "the planned setup of experiments",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "featTiers": {
                    "type": "integer"
                },
                "groupBonusCount": {
                    "description": "Number of times group bonuses can be claimed (default 1)",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "leftoverShards": {
                    "description": "Shards remaining from previous prestige",
                    "type": "integer"
                },
                "legendaryCounts": {
                    "description": "the planned amount of legendaries",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "otherMultiplier": {
                    "description": "The \"Other\" category (skins, etc.)",
                    "type": "number"
                },
                "possessedLegendaries": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "possessedRunes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8085",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Necro Prestige Planner API",
	Description:      "API for planning prestige resets and experiment spending in Necromerger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
